# nginx proxy address - http://172.17.0.1:3003

name: excalidraw
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    pull_policy: always
    container_name: excalidraw-app
    restart: always
    logging: *default-logging
    networks:
      - excalidraw
    ports:
      - "172.17.0.1:3003:80"
    environment:
      TZ: ${TZ:-America/New_York}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  excalidraw:
    name: excalidraw
    external: false
